//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barang
    {
        public Barang()
        {
            this.Pengurangan_Stock = new HashSet<Pengurangan_Stock>();
            this.Stocks = new HashSet<Stock>();
            this.Pembelian_Detail = new HashSet<Pembelian_Detail>();
            this.Penjualan_Detail = new HashSet<Penjualan_Detail>();
        }
    
        public string id_barang { get; set; }
        public string nama_barang { get; set; }
        public Nullable<decimal> harga_jual { get; set; }
        public string barcode { get; set; }
        public string deskripsi { get; set; }
        public Nullable<bool> discontinued { get; set; }
    
        public virtual ICollection<Pengurangan_Stock> Pengurangan_Stock { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<Pembelian_Detail> Pembelian_Detail { get; set; }
        public virtual ICollection<Penjualan_Detail> Penjualan_Detail { get; set; }
    }
}
