//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_petshopEntities1 : DbContext
    {
        public db_petshopEntities1()
            : base("name=db_petshopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BackupTrackRecord> BackupTrackRecords { get; set; }
        public DbSet<Barang> Barangs { get; set; }
        public DbSet<Pembelian> Pembelians { get; set; }
        public DbSet<Pengguna> Penggunas { get; set; }
        public DbSet<Pengurangan_Stock> Pengurangan_Stock { get; set; }
        public DbSet<Penjualan> Penjualans { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Pembelian_Detail> Pembelian_Detail { get; set; }
        public DbSet<Penjualan_Detail> Penjualan_Detail { get; set; }
        public DbSet<Stock> Stocks { get; set; }
    }
}
