//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pembelian
    {
        public Pembelian()
        {
            this.Pengurangan_Stock = new HashSet<Pengurangan_Stock>();
            this.Stocks = new HashSet<Stock>();
            this.Pembelian_Detail = new HashSet<Pembelian_Detail>();
        }
    
        public string id_pembelian { get; set; }
        public string id_supplier { get; set; }
        public Nullable<System.DateTime> tgl_pembelian { get; set; }
        public Nullable<decimal> grandTotal { get; set; }
    
        public virtual ICollection<Pengurangan_Stock> Pengurangan_Stock { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<Pembelian_Detail> Pembelian_Detail { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
