//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penjualan
    {
        public Penjualan()
        {
            this.Penjualan_Detail = new HashSet<Penjualan_Detail>();
        }
    
        public string id_penjualan { get; set; }
        public Nullable<System.DateTime> tgl_transaksi { get; set; }
        public Nullable<decimal> total_harga { get; set; }
        public Nullable<decimal> potongan { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> dibayarkan { get; set; }
        public Nullable<decimal> kembalian { get; set; }
    
        public virtual ICollection<Penjualan_Detail> Penjualan_Detail { get; set; }
    }
}
