//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penjualan_Detail
    {
        public string id_penjualan { get; set; }
        public string id_barang { get; set; }
        public Nullable<int> qty_jual { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<decimal> harga_jual { get; set; }
        public Nullable<decimal> harga_beli { get; set; }
    
        public virtual Barang Barang { get; set; }
        public virtual Penjualan Penjualan { get; set; }
    }
}
