//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Pembelians = new HashSet<Pembelian>();
        }
    
        public string id_supplier { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public string provinsi { get; set; }
        public string kota { get; set; }
        public string telp { get; set; }
        public string email { get; set; }
        public string deskripsi { get; set; }
    
        public virtual ICollection<Pembelian> Pembelians { get; set; }
    }
}
